# Generated by Django 2.0 on 2019-06-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20190525_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='me',
            old_name='ID_number',
            new_name='Id_number',
        ),
    ]
