# Generated by Django 2.0 on 2019-06-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20190603_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='egg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=15)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='me',
        ),
    ]
